Volatile & Reloadable.distinctByKey
fit51/reactive-config pull request #13
Opened 2020-02-25 12:46 UTC by danilbykov

1. Bump cats version
2. Add new method `Reloadable.distinctByKey` to filter out duplicated events
3. Add new trait `Volatile` which is simplified `Reloadable` but `Volatile` has method `mapK` which allows to change its context. This method can not be implemented on `Reloadable` because effect `F` is contained in both covariant and contravariant positions. `Volatile` has simpler interface with `F` only in covariant position.

2020-03-04 13:52 UTC, fit51 requested changes
Please, remove mapK from ReloadBehaviour

2020-03-04 13:52 UTC, fit51 commented on core/src/main/scala/com/github/fit51/reactiveconfig/reloadable/ReloadBehaviour.scala
> +  def mapK[G[_]](fk: F ~> G): ReloadBehaviour[G, A, B]
In the end, this method is not used.

2020-03-05 07:12 UTC, danilbykov commented on core/src/main/scala/com/github/fit51/reactiveconfig/reloadable/ReloadBehaviour.scala
> +  def mapK[G[_]](fk: F ~> G): ReloadBehaviour[G, A, B]
Done.

2020-03-11 12:01 UTC, fit51 approved these changes

2020-03-11 12:01 UTC, fit51 commented on build.sbt
> +      "io.circe"       %% "circe-generic"  % circeVersion % Provided
```suggestion
      "io.circe"       %% "circe-generic"  % circeVersion,
      "io.circe"       %% "circe-parser"   % circeVersion
```

2020-03-11 12:01 UTC, merged